### ISSUE TITLE
Can't get build.w.o to run locally

### ISSUE THREAD

**Issue by adamlofting** [mozilla/build.webmaker.org#65]
I have been able to work on this project in the past, but it might have been pre-react.

I just did a fresh:
- clone
- npm insall
- gulp liveserve

Gulp runs as follows:
![screen shot 2015-03-20 at 15 52 24](https://cloud.githubusercontent.com/assets/1901816/6755272/bb4036d6-cf19-11e4-882a-438019325707.png)

There's a bunch of JS style validation errors, but I don't think they are causing any problems.

If I then try to view the site, I get nothing:

![screen shot 2015-03-20 at 15 52 40](https://cloud.githubusercontent.com/assets/1901816/6755288/d90e2754-cf19-11e4-9ce0-868c70ceb657.png)

I don't seem to ever get to the `Server listening on port ...`, even though Gulp does start `serve`:

``` bash
[15:51:39] Starting 'serve'...
[15:51:39] Finished 'serve' after 40 ms
```

**Comment by adamlofting** [comment]
@simonwex @gvn 

I switched out `gulp-express` for `gulp-live-server` to see if that would give me any clues. 

It is giving me some error output now

``` bash
/Users/alofting-10317/Sites/build.webmaker.org/node_modules/firebase/lib/firebase-node.js:133
Can't modify data under /.info/");}function Xf(a,b){if(!p(b))throw Error(z(a,
                                                                    ^
Error: Firebase.authWithCustomToken failed: First argument must be a valid credential (a string).
    at Error (<anonymous>)
    at Xf (/Users/alofting-10317/Sites/build.webmaker.org/node_modules/firebase/lib/firebase-node.js:133:313)
    at T.Sf (/Users/alofting-10317/Sites/build.webmaker.org/node_modules/firebase/lib/firebase-node.js:250:87)
    at Object.<anonymous> (/Users/alofting-10317/Sites/build.webmaker.org/server/issueparser.js:12:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

I don't have a `FIREBASE_SECRET` in .env which might be the problem. https://github.com/mozilla/build.webmaker.org/blob/master/server/config/secrets.js#L9

**Comment by adamlofting** [comment]
Adding a `FIREBASE_SECRET` from a new personal Firebase hacker plan has worked for me.

**Comment by adamlofting** [comment]
Hmmm... re-opening this, as it doesn't work when I switch back to `gulp-express`

**Comment by thisandagain** [comment]
Confirmed on my end as well. Running @adamlofting 's patch in the meantime.

**Comment by davidascher** [comment]
Will look.
